### PR TITLE
Added themes, a header and changed the width+height

### PR DESCRIPTION
**Pull request by jeroenpraat**
The light theme is the default (like Focus on Hubzilla). The 300 width gives it just a bit more space, same for the 12000 height.

### CODE REVIEW

**Comment by zotlabs** [comment]
But - the aside or right_aside region that you're typically putting it in is only 288 pixels wide. Perhaps these should all be options, but I think the sane default is the aside width (or slightly less) - and perhaps 2-3 vertical pages rather than 10 or more; which means you can never really put another widget underneath it. I'll leave these decisions to others since I have no reason to use this widget, but that's my thinking.

**Comment by jeroenpraat** [comment]
Oh that's odd, I can make it as wide as I like. Yes, you're right about the vertical height. And probably that also needs some options. I change those numbers back and maybe back later to add args for those.

**Comment by jeroenpraat** [comment]
Oh and BTW @zotlabs : Thank you for this widget!

**Comment by zotlabs** [comment]
It's all from your post - I just wrapped it so folks can use it without code permission.

**Pull request merged**
